Repository sschipke/palette-producer, pull requests merged in 2019-12, with the labels that each got.

#13 Ss login
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/App/App.scss
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.scss
  src/components/LoginForm/LoginForm.test.js
  src/components/LoginForm/__snapshots__/LoginForm.test.js.snap
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.test.js
  src/components/SignupForm/SignupForm.js
  src/components/SignupForm/SignupForm.scss
  src/components/SignupForm/SignupForm.test.js
  src/components/SignupForm/__snapshots__/SignupForm.test.js.snap
  src/util/apiCalls.js
  src/util/apiCalls.test.js
Labels: api consumption, mvp, testing

#17 Style
  src/components/App/App.js
  src/components/PaletteCard/PaletteCard.js
  src/components/PaletteCard/PaletteCard.scss
  src/components/ProjectCard/ProjectCard.js
  src/components/ProjectCard/ProjectCard.scss
  src/components/ProjectContainer/ProjectContainer.js
  src/components/ProjectContainer/ProjectContainer.scss
Labels: mvp

#21 Ss testing
  package.json
  src/components/ColorCard/ColorCard.test.js
  src/components/ColorCard/__snapshots__/ColorCard.test.js.snap
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.test.js
  src/components/LoginForm/__snapshots__/LoginForm.test.js.snap
  src/components/Modal/Modal.test.js
  src/components/Modal/__snapshots__/Modal.test.js.snap
  src/components/Nav/Nav.test.js
  src/components/Nav/__snapshots__/Nav.test.js.snap
  src/components/PaletteCard/PaletteCard.js
  src/components/PaletteCard/PaletteCard.test.js
  src/components/PaletteCard/__snapshots__/PaletteCard.test.js.snap
  src/components/PaletteContainer/PaletteContainer.js
  src/components/PaletteContainer/PaletteContainer.test.js
  src/components/PaletteContainer/__snapshots__/PaletteContainer.test.js.snap
  src/components/ProjectCard/ProjectCard.js
  src/components/ProjectCard/ProjectCard.test.js
  src/components/ProjectCard/__snapshots__/ProjectCard.test.js.snap
  src/components/ProjectContainer/ProjectContainer.test.js
  src/components/ProjectContainer/__snapshots__/ProjectContainer.test.js.snap
  src/components/SignupForm/SignupForm.js
  src/components/SignupForm/SignupForm.test.js
  src/util/apiCalls.js
  src/util/apiCalls.test.js
Labels: testing

#23 Fix save bug
  src/components/App/App.js
Labels: bug
